from enum import Enum


class TaskType(Enum):
    CLASSIFICATION_BINARY = 0
    CLASSIFICATION_SINGLE_LABEL = 1
    CLASSIFICATION_MULTI_LABEL = 2
    OBJECT_DETECTION = 3
    INSTANCE_SEGMENTATION = 4
    TS_CLASSIFICATION = 5
    TS_FORECASTING = 6
    TS_ANOMALY_DETECTION = 7
    TS_PREDICTIVE_MAINTENANCE = 8
