from enum import Enum

class TaskType(Enum):
    CLASSIFICATION_BINARY = 0
    CLASSIFICATION_SINGLE_LABEL = 1
    CLASSIFICATION_MULTI_LABEL = 2
    OBJECT_DETECTION = 3
    INSTANCE_SEGMENTATION = 4
